/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseId = bigint;
export interface LegalCase {
  'status' : string,
  'title' : string,
  'underSection' : string,
  'clientName' : string,
  'clientAddress' : string,
  'clientContact' : string,
  'court' : string,
  'refNumber' : string,
  'nextDate' : bigint,
  'hearingReason' : string,
  'partiesName' : string,
  'remarks' : string,
}
export interface CaseWithId {
  'id' : bigint,
  'legalCase' : LegalCase,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Create a new legal case.
   */
  'addCase' : ActorMethod<[LegalCase], CaseId>,
  /**
   * / Update an existing case.
   */
  'updateCase' : ActorMethod<[bigint, LegalCase], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete a case by id (only if created by caller).
   */
  'deleteCase' : ActorMethod<[CaseId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get all cases for the caller.
   */
  'getMyCases' : ActorMethod<[], Array<LegalCase>>,
  /**
   * / Get all cases for the caller with their IDs.
   */
  'getMyCasesWithId' : ActorMethod<[], Array<CaseWithId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
