/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LegalCase = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'underSection' : IDL.Text,
  'clientName' : IDL.Text,
  'clientAddress' : IDL.Text,
  'clientContact' : IDL.Text,
  'court' : IDL.Text,
  'refNumber' : IDL.Text,
  'nextDate' : IDL.Nat,
  'hearingReason' : IDL.Text,
  'partiesName' : IDL.Text,
  'remarks' : IDL.Text,
});
export const CaseId = IDL.Nat;
export const CaseWithId = IDL.Record({
  'id' : IDL.Nat,
  'legalCase' : LegalCase,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCase' : IDL.Func([LegalCase], [CaseId], []),
  'updateCase' : IDL.Func([IDL.Nat, LegalCase], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCase' : IDL.Func([CaseId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyCases' : IDL.Func([], [IDL.Vec(LegalCase)], ['query']),
  'getMyCasesWithId' : IDL.Func([], [IDL.Vec(CaseWithId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LegalCase = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'underSection' : IDL.Text,
    'clientName' : IDL.Text,
    'clientAddress' : IDL.Text,
    'clientContact' : IDL.Text,
    'court' : IDL.Text,
    'refNumber' : IDL.Text,
    'nextDate' : IDL.Nat,
    'hearingReason' : IDL.Text,
    'partiesName' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const CaseId = IDL.Nat;
  const CaseWithId = IDL.Record({
    'id' : IDL.Nat,
    'legalCase' : LegalCase,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCase' : IDL.Func([LegalCase], [CaseId], []),
    'updateCase' : IDL.Func([IDL.Nat, LegalCase], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCase' : IDL.Func([CaseId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyCases' : IDL.Func([], [IDL.Vec(LegalCase)], ['query']),
    'getMyCasesWithId' : IDL.Func([], [IDL.Vec(CaseWithId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
